VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClassSpliterConstants"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'--> Clase con las constantes de los spliter
Option Explicit

Public Enum SpliterBorder 'Constantes con el borde del spliter
  SplBorderNone = 0 'Sin borde
  SplBorderSolid = 1 'Con borde sólido
End Enum
